# Generated by Django 4.2.7 on 2024-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
